title: Welcome to SavioSeal's blog!
author: SavioSeal
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is a testing blog to learn how to use GitHub!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  savioseal # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
